---
title: "HW5_write_up"
author: "Seré Williams"
date: "11/11/2019"
output:
  word_document: default
  html_document: default
  pdf_document: default
---

```{r global options}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, error = FALSE)
```

## Load Libraries

```{r load libraries}
library(readr)
library(dplyr)
library(tidyr)
library(ggplot2)
library(sf)
library(tigris)
options(tigris_class = "sf")
library(scales)
library(forcats)
```

## Load and clean the homicide data. Filter for Chicago and modify victim_race and disposition vectors.

```{r}
homicide <- read_csv("../data/homicide-data.csv")
chicago <- homicide %>% 
  filter(city == "Chicago") %>% 
  mutate(victim_race = fct_lump(victim_race, n = 3)) %>% 
  mutate(disposition = as_factor(x = disposition),
         disposition = fct_recode(.f = disposition,
                                  Solved = "Closed by arrest",
                                  Unsolved = "Closed without arrest",
                                  Unsolved = "Open/No arrest"))

```

## Practice with counties using sf and tigris.

```{r}
il_counties <- counties(state = "IL", cb = TRUE, class = "sf")
class(il_counties)
il_counties %>% 
  slice(1:3)
class(il_counties$geometry)

ggplot() +
  geom_sf(data = il_counties)

```


## Narrow in on Chicago (Cook County).

```{r}
cook <- il_counties %>% 
  filter(NAME == "Cook")
cook

ggplot() +
  geom_sf(data = il_counties, color = "lightgray") +
  geom_sf(data = cook, fill = "darkcyan") +
  geom_sf_text(data = cook, aes(label = NAME),
               color = "white",
               nudge_y = .26) +
  theme_dark() +
  labs(x = "", y = "")
```



## Consider tracts.
```{r}
cook_tracts <- tracts("IL", county = "cook", cb = TRUE)

ggplot() +
  geom_sf(data = cook_tracts, color = "darkblue") +
  theme_dark() +
  labs(x = "", y = "")

```




## Making sf object of lat and lon in homicide dataset and create plot.

```{r fig.width=6, fig.height=10}
il_point <- st_as_sf(chicago, coords=c("lon", "lat")) %>%
  st_set_crs(4269)

ggplot() +
  geom_sf(data = cook_tracts, color = "goldenrod2") +
  geom_sf(data = il_point, aes(color = victim_race, fill = victim_race)) +
  theme_dark() +
  labs(x = "", y = "") +
  facet_wrap(~ disposition) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  ggtitle("Homicides in Chicago, IL") 
  
```

